# -*- coding: utf-8 -*-
"""reto_financiero (1) (1).ipynb
 
Automatically generated by Colab.
 
Original file is located at
    https://colab.research.google.com/drive/1v2rphGxe3MOdVy-w5U_da48qVVnx3QhM
"""

# Celda 2: importar
import streamlit as st                         # Crear aplicaciones web interactivas
import yfinance as yf                          # Descarga datos financieros de Yahoo Finance
import pandas as pd                            # Análisis y manipulación de datos tabulares
import numpy as np                             # Cálculo numérico y álgebra vectorial
import plotly.express as px                    # Gráficos interactivos de alto nivel
import plotly.graph_objects as go              # Gráficos interactivos de bajo nivel (control total)
from plotly.subplots import make_subplots      # Crear cuadrículas de gráficos (subplots)
from datetime import datetime, timedelta       # Manejo de fechas y diferencias de tiempo
from scipy import stats                        # Estadísticas: curtosis, sesgo, normalidad
import warnings                                # Suprimir advertencias no críticas
warnings.filterwarnings('ignore')
print("¡Comencemos con el fondo de criptos!")

# Creemos una lista para nuestras criptos a analizar
criptos = ["BTC-USD", "ETH-USD", "SOL-USD", "ADA-USD", "LTC-USD"]

# Nombre completo de cada criptomoneda
NOMBRES = {
    'BTC-USD': 'Bitcoin',
    'ETH-USD': 'Ethereum',
    'SOL-USD': 'Solana',
    'LTC-USD': 'Litecoin',
    'ADA-USD': 'Cardano',
}

# Descarguemos la informacion desde yahoo finance

eth = yf.download('ETH-USD',
       start='2025-01-01',
       end='2026-05-20',
       interval='1d')

btc = yf.download('BTC-USD',
       start='2025-01-01',
       end='2026-05-20',
       interval='1d')

sol = yf.download('SOL-USD',
       start='2025-01-01',
       end='2026-05-20',
       interval='1d')
ada= yf.download('ADA-USD',
      start='2025-01-01',
      end='2026-05-20',
      interval='1d')

ltc= yf.download('LTC-USD',
      start='2025-01-01',
      end='2026-05-20',
      interval='1d')

# Benchmark del mercado cripto → usamos BTC como referencia dominante
BENCHMARK = 'BTC-USD'

# Paleta de colores asignada a cada cripto (para consistencia visual)
COLORS = {
    'BTC-USD': '#F7931A',    # Naranja Bitcoin
    'ETH-USD': '#627EEA',    # Azul Ethereum
    'SOL-USD': '#9945FF',    # Morado Solana
    'LTC-USD': '#F3BA2F',    # Amarillo Litecoin
    'ADA-USD': '#0D1E2D',    # Azul oscuro Cardano
}

# veamos las primeras 5 filas
btc.head()
eth.head()
sol.head()
ada.head()
ltc.head()

df_close = pd.DataFrame()

for ticker in criptos:
    # Acceder a la columna 'Close' usando el MultiIndex
    if ticker == 'BTC-USD': df_close[ticker] = btc[('Close', ticker)]
    elif ticker == 'ETH-USD': df_close[ticker] = eth[('Close', ticker)]
    elif ticker == 'SOL-USD': df_close[ticker] = sol[('Close', ticker)]
    elif ticker == 'ADA-USD': df_close[ticker] = ada[('Close', ticker)]
    elif ticker == 'LTC-USD': df_close[ticker] = ltc[('Close', ticker)]

# Calcular los retornos diarios
df_returns = df_close.pct_change().dropna()

# Calcular los retornos acumulados
df_cumulative_returns = (1 + df_returns).cumprod() - 1

# Crear el gráfico de líneas con Plotly Go
fig = go.Figure()

for ticker in criptos:
    fig.add_trace(go.Scatter(
        x=df_cumulative_returns.index,
        y=df_cumulative_returns[ticker],
        mode='lines',
        name=NOMBRES[ticker],
        line=dict(color=COLORS[ticker])
    ))

fig.update_layout(
    title_text='Rendimiento Acumulado de Criptomonedas',
    xaxis_title='Fecha',
    yaxis_title='Retorno Acumulado',
    hovermode='x unified',
    template='plotly_dark'
)

fig.show()

fig_historical = go.Figure()

for ticker in criptos:
    fig_historical.add_trace(go.Scatter(
        x=df_close.index,
        y=df_close[ticker],
        mode='lines',
        name=NOMBRES[ticker],
        line=dict(color=COLORS[ticker])
    ))

fig_historical.update_layout(
    title_text='Precios Históricos de Criptomonedas (Cierre)',
    xaxis_title='Fecha',
    yaxis_title='Precio (USD)',
    hovermode='x unified',
    template='plotly_dark'
)

fig_historical.show()

fig_daily_returns = go.Figure()

for ticker in criptos:
    fig_daily_returns.add_trace(go.Scatter(
        x=df_returns.index,
        y=df_returns[ticker],
        mode='lines',
        name=NOMBRES[ticker],
        line=dict(color=COLORS[ticker])
    ))

fig_daily_returns.update_layout(
    title_text='Rendimientos Diarios de Criptomonedas',
    xaxis_title='Fecha',
    yaxis_title='Retorno Diario',
    hovermode='x unified',
    template='plotly_dark'
)

fig_daily_returns.show()

df_weekly_close = df_close.resample('W').last()
df_weekly_returns = df_weekly_close.pct_change().dropna()

fig_weekly_returns = go.Figure()

for ticker in criptos:
    fig_weekly_returns.add_trace(go.Scatter(
        x=df_weekly_returns.index,
        y=df_weekly_returns[ticker],
        mode='lines',
        name=NOMBRES[ticker],
        line=dict(color=COLORS[ticker])
    ))

fig_weekly_returns.update_layout(
    title_text='Rendimientos Semanales de Criptomonedas',
    xaxis_title='Fecha',
    yaxis_title='Retorno Semanal',
    hovermode='x unified',
    template='plotly_dark'
)

fig_weekly_returns.show()

df_monthly_close = df_close.resample('M').last()
df_monthly_returns = df_monthly_close.pct_change().dropna()

fig_monthly_returns = go.Figure()

for ticker in criptos:
    fig_monthly_returns.add_trace(go.Scatter(
        x=df_monthly_returns.index,
        y=df_monthly_returns[ticker],
        mode='lines',
        name=NOMBRES[ticker],
        line=dict(color=COLORS[ticker])
    ))

fig_monthly_returns.update_layout(
    title_text='Rendimientos Mensuales de Criptomonedas',
    xaxis_title='Fecha',
    yaxis_title='Retorno Mensual',
    hovermode='x unified',
    template='plotly_dark'
)

fig_monthly_returns.show()

df_weekly_close = df_close.resample('W').last()
df_weekly_returns = df_weekly_close.pct_change().dropna()

fig_weekly_returns = go.Figure()

for ticker in criptos:
    fig_weekly_returns.add_trace(go.Scatter(
        x=df_weekly_returns.index,
        y=df_weekly_returns[ticker],
        mode='lines',
        name=NOMBRES[ticker],
        line=dict(color=COLORS[ticker])
    ))

fig_weekly_returns.update_layout(
    title_text='Rendimientos Semanales de Criptomonedas',
    xaxis_title='Fecha',
    yaxis_title='Retorno Semanal',
    hovermode='x unified',
    template='plotly_dark'
)

fig_weekly_returns.show()

print("Desviación Estándar de los Rendimientos Diarios:")
print(df_returns.std())

std_devs = df_returns.std().reset_index()
std_devs.columns = ['Cripto', 'Desviacion_Estandar']

fig_std_dev = px.bar(
    std_devs,
    x='Cripto',
    y='Desviacion_Estandar',
    title='Desviación Estándar de los Rendimientos Diarios',
    color='Cripto',
    color_discrete_map=COLORS,
    labels={'Desviacion_Estandar': 'Desviación Estándar'},
    template='plotly_dark'
)

fig_std_dev.update_layout(
    xaxis_title='Criptomoneda',
    yaxis_title='Desviación Estándar',
    hovermode='x unified'
)

fig_std_dev.show()

max_drawdowns = {}

for ticker in criptos:
    # Calcular los retornos acumulados
    cumulative_returns = (1 + df_returns[ticker]).cumprod()

    # Calcular el máximo histórico (peak) hasta cada punto
    rolling_max = cumulative_returns.expanding().max()

    # Calcular el Drawdown
    drawdown = (rolling_max - cumulative_returns) / rolling_max

    # La máxima caída es el valor máximo del drawdown
    max_drawdowns[ticker] = drawdown.max()

# Convertir el diccionario a un DataFrame para Plotly
df_max_drawdowns = pd.DataFrame(max_drawdowns.items(), columns=['Cripto', 'Max_Drawdown'])

# Crear el gráfico de barras para la Máxima Caída
fig_drawdown = px.bar(
    df_max_drawdowns,
    x='Cripto',
    y='Max_Drawdown',
    title='Máxima Caída (Max Drawdown) por Criptomoneda',
    color='Cripto',
    color_discrete_map=COLORS,
    labels={'Max_Drawdown': 'Máxima Caída'},
    template='plotly_dark'
)

fig_drawdown.update_layout(
    xaxis_title='Criptomoneda',
    yaxis_title='Máxima Caída (%)',
    hovermode='x unified',
    yaxis_tickformat='.2%'
)

fig_drawdown.show()

loss_frequency = (df_returns < 0).sum() / len(df_returns)

df_loss_frequency = loss_frequency.reset_index()
df_loss_frequency.columns = ['Cripto', 'Frecuencia_Perdidas']

fig_loss_freq = px.bar(
    df_loss_frequency,
    x='Cripto',
    y='Frecuencia_Perdidas',
    title='Frecuencia de Días con Pérdidas por Criptomoneda',
    color='Cripto',
    color_discrete_map=COLORS,
    labels={'Frecuencia_Perdidas': 'Frecuencia de Pérdidas'},
    template='plotly_dark'
)

fig_loss_freq.update_layout(
    xaxis_title='Criptomoneda',
    yaxis_title='Frecuencia de Pérdidas (%)',
    hovermode='x unified',
    yaxis_tickformat='.2%'
)

fig_loss_freq.show()

btc.describe()
eth.describe()
sol.describe()
ada.describe()
ltc.describe()

daily_avg_returns = df_returns.mean()
correlation_matrix = df_returns.corr()

print("Rendimientos Diarios Promedio:")
print(daily_avg_returns)

print("\nMatriz de Correlación de Rendimientos Diarios:")
print(correlation_matrix)

risk_profile = pd.merge(std_devs, df_max_drawdowns, on='Cripto')
risk_profile = pd.merge(risk_profile, df_loss_frequency, on='Cripto')

risk_profile.columns = ['Criptomoneda', 'Volatilidad (Desv. Estándar)', 'Máxima Caída (Max Drawdown)', 'Frecuencia de Pérdidas']

print("\nPerfil de Riesgo de Cada Criptomoneda:")
print(risk_profile.set_index('Criptomoneda'))

print("### Propuesta de Asignación de Portafolio Conservador ###\n")

# Definir las ponderaciones del portafolio conservador
# Se prioriza BTC por su menor volatilidad y max drawdown, seguido de ETH y LTC.
# SOL y ADA reciben una asignación mínima debido a sus mayores perfiles de riesgo.
conservative_weights = {
    'BTC-USD': 0.60,
    'ETH-USD': 0.20,
    'LTC-USD': 0.15,
    'SOL-USD': 0.025,
    'ADA-USD': 0.025
}

# Convertir las ponderaciones a un DataFrame para fácil manejo
df_weights = pd.DataFrame(list(conservative_weights.items()), columns=['Criptomoneda', 'Peso'])
df_weights['Criptomoneda'] = df_weights['Criptomoneda'].map(NOMBRES) # Usar nombres completos

print("**Ponderaciones del Portafolio Conservador:**")
for crypto, weight in conservative_weights.items():
    print(f"- {NOMBRES[crypto]}: {weight:.1%}")

# Calcular el rendimiento esperado anualizado del portafolio
# Usamos los daily_avg_returns calculados previamente (promedio histórico)
portfolio_expected_daily_return = sum(daily_avg_returns[ticker] * conservative_weights[ticker] for ticker in criptos)
portfolio_expected_annual_return = portfolio_expected_daily_return * 365 # Anualizamos

# Calcular la volatilidad anualizada del portafolio
# Necesitamos la matriz de covarianza de los retornos diarios
cov_matrix = df_returns.cov()

# Crear un vector de ponderaciones en el orden correcto para la matriz de covarianza
weights_vector = np.array([conservative_weights[ticker] for ticker in criptos])

# Calcular la varianza del portafolio
portfolio_variance = np.dot(weights_vector.T, np.dot(cov_matrix, weights_vector))

# Calcular la volatilidad anualizada del portafolio
portfolio_annual_volatility = np.sqrt(portfolio_variance) * np.sqrt(365)

print(f"\n**Rendimiento Esperado Anualizado del Portafolio:** {portfolio_expected_annual_return:.2%}")
print(f"**Volatilidad Esperada Anualizada del Portafolio:** {portfolio_annual_volatility:.2%}")

# Visualizar la asignación del portafolio
fig_allocation = px.pie(
    df_weights,
    values='Peso',
    names='Criptomoneda',
    title='Asignación del Portafolio Conservador',
    color='Criptomoneda',
    color_discrete_map={NOMBRES[k]: COLORS[k] for k in criptos},
    hole=0.3 # Para un gráfico de donut
)

fig_allocation.update_traces(textinfo='percent+label', pull=[0.05 if df_weights['Criptomoneda'][i] == NOMBRES['BTC-USD'] else 0 for i in range(len(df_weights))])
fig_allocation.update_layout(
    template='plotly_dark',
    legend_title_text='Criptomoneda'
)

fig_allocation.show()

print("\n**Justificación de la Asignación:**\n")
print("El portafolio conservador busca la preservación del capital con un crecimiento moderado y estable. \n" \
      "Por lo tanto, se asigna la mayor parte a Bitcoin (BTC-USD), que presenta la menor volatilidad y el menor Maximum Drawdown entre las criptomonedas analizadas, \n" \
      "lo que lo convierte en la opción más estable. Ethereum (ETH-USD) y Litecoin (LTC-USD) reciben una asignación moderada \n" \
      "debido a su perfil de riesgo relativamente inferior en comparación con Solana y Cardano, pero aún ofreciendo potencial de crecimiento.\n" \
      "Solana (SOL-USD) y Cardano (ADA-USD) tienen la menor asignación debido a sus mayores niveles de volatilidad, Maximum Drawdown y frecuencia de pérdidas, \n" \
      "lo que los hace más adecuados para inversores con mayor tolerancia al riesgo en un contexto general de portafolio conservador.")

print("\n### Propuesta de Asignación de Portafolio Moderado ###\n")

# Definir las ponderaciones del portafolio moderado
# Busca un equilibrio entre el crecimiento del capital y la gestión del riesgo.
# Aumenta la exposición a ETH, SOL y ADA, reduciendo ligeramente BTC.
moderate_weights = {
    'BTC-USD': 0.40,
    'ETH-USD': 0.30,
    'LTC-USD': 0.15,
    'SOL-USD': 0.075,
    'ADA-USD': 0.075
}

# Convertir las ponderaciones a un DataFrame para fácil manejo
df_weights_moderate = pd.DataFrame(list(moderate_weights.items()), columns=['Criptomoneda', 'Peso'])
df_weights_moderate['Criptomoneda'] = df_weights_moderate['Criptomoneda'].map(NOMBRES) # Usar nombres completos

print("**Ponderaciones del Portafolio Moderado:**")
for crypto, weight in moderate_weights.items():
    print(f"- {NOMBRES[crypto]}: {weight:.1%}")

# Calcular el rendimiento esperado anualizado del portafolio moderado
portfolio_expected_daily_return_moderate = sum(daily_avg_returns[ticker] * moderate_weights[ticker] for ticker in criptos)
portfolio_expected_annual_return_moderate = portfolio_expected_daily_return_moderate * 365 # Anualizamos

# Calcular la volatilidad anualizada del portafolio moderado
weights_vector_moderate = np.array([moderate_weights[ticker] for ticker in criptos])
portfolio_variance_moderate = np.dot(weights_vector_moderate.T, np.dot(cov_matrix, weights_vector_moderate))
portfolio_annual_volatility_moderate = np.sqrt(portfolio_variance_moderate) * np.sqrt(365)

print(f"\n**Rendimiento Esperado Anualizado del Portafolio Moderado:** {portfolio_expected_annual_return_moderate:.2%}")
print(f"**Volatilidad Esperada Anualizada del Portafolio Moderado:** {portfolio_annual_volatility_moderate:.2%}")

# Visualizar la asignación del portafolio moderado
fig_allocation_moderate = px.pie(
    df_weights_moderate,
    values='Peso',
    names='Criptomoneda',
    title='Asignación del Portafolio Moderado',
    color='Criptomoneda',
    color_discrete_map={NOMBRES[k]: COLORS[k] for k in criptos},
    hole=0.3 # Para un gráfico de donut
)

fig_allocation_moderate.update_traces(textinfo='percent+label', pull=[0.05 if df_weights_moderate['Criptomoneda'][i] == NOMBRES['ETH-USD'] else 0 for i in range(len(df_weights_moderate))])
fig_allocation_moderate.update_layout(
    template='plotly_dark',
    legend_title_text='Criptomoneda'
)

fig_allocation_moderate.show()

print("\n**Justificación de la Asignación Moderada:**\n")
print("El portafolio moderado busca un equilibrio entre la seguridad del capital y el potencial de crecimiento. \n" \
      "Mantiene una exposición significativa a Bitcoin (BTC-USD) como base estable, pero aumenta la asignación a Ethereum (ETH-USD) y Litecoin (LTC-USD) \n" \
      "para capturar un mayor crecimiento potencial con un riesgo manejable. La exposición a Solana (SOL-USD) y Cardano (ADA-USD) también se incrementa, \n" \
      "aunque siguen siendo posiciones más pequeñas debido a su mayor volatilidad, para aprovechar sus oportunidades de alto crecimiento a largo plazo.")

print("\n### Propuesta de Asignación de Portafolio Arriesgado ###\n")

# Definir las ponderaciones del portafolio arriesgado
# Prioriza SOL y ADA para maximizar el crecimiento de capital, aceptando un alto nivel de riesgo.
# BTC y ETH tienen una asignación menor comparado con los otros portafolios.
risky_weights = {
    'BTC-USD': 0.20,
    'ETH-USD': 0.25,
    'LTC-USD': 0.10,
    'SOL-USD': 0.225,
    'ADA-USD': 0.225
}

# Convertir las ponderaciones a un DataFrame para fácil manejo
df_weights_risky = pd.DataFrame(list(risky_weights.items()), columns=['Criptomoneda', 'Peso'])
df_weights_risky['Criptomoneda'] = df_weights_risky['Criptomoneda'].map(NOMBRES) # Usar nombres completos

print("**Ponderaciones del Portafolio Arriesgado:**")
for crypto, weight in risky_weights.items():
    print(f"- {NOMBRES[crypto]}: {weight:.1%}")

# Calcular el rendimiento esperado anualizado del portafolio arriesgado
portfolio_expected_daily_return_risky = sum(daily_avg_returns[ticker] * risky_weights[ticker] for ticker in criptos)
portfolio_expected_annual_return_risky = portfolio_expected_daily_return_risky * 365 # Anualizamos

# Calcular la volatilidad anualizada del portafolio arriesgado
weights_vector_risky = np.array([risky_weights[ticker] for ticker in criptos])
portfolio_variance_risky = np.dot(weights_vector_risky.T, np.dot(cov_matrix, weights_vector_risky))
portfolio_annual_volatility_risky = np.sqrt(portfolio_variance_risky) * np.sqrt(365)

print(f"\n**Rendimiento Esperado Anualizado del Portafolio Arriesgado:** {portfolio_expected_annual_return_risky:.2%}")
print(f"**Volatilidad Esperada Anualizada del Portafolio Arriesgado:** {portfolio_annual_volatility_risky:.2%}")

# Visualizar la asignación del portafolio arriesgado
fig_allocation_risky = px.pie(
    df_weights_risky,
    values='Peso',
    names='Criptomoneda',
    title='Asignación del Portafolio Arriesgado',
    color='Criptomoneda',
    color_discrete_map={NOMBRES[k]: COLORS[k] for k in criptos},
    hole=0.3 # Para un gráfico de donut
)

fig_allocation_risky.update_traces(textinfo='percent+label', pull=[0.05 if df_weights_risky['Criptomoneda'][i] == NOMBRES['SOL-USD'] else 0 for i in range(len(df_weights_risky))])
fig_allocation_risky.update_layout(
    template='plotly_dark',
    legend_title_text='Criptomoneda'
)

fig_allocation_risky.show()

print("\n**Justificación de la Asignación Arriesgada:**\n")
print("El portafolio arriesgado está diseñado para inversores que buscan maximizar el crecimiento del capital \n" \
      "y están dispuestos a aceptar un alto nivel de riesgo y volatilidad. Se reduce la exposición a activos más estables como Bitcoin (BTC-USD) y Ethereum (ETH-USD) \n" \
      "para aumentar significativamente la asignación a Solana (SOL-USD) y Cardano (ADA-USD), que históricamente han demostrado mayor volatilidad \n" \
      "pero también un mayor potencial de rendimiento en mercados alcistas. Litecoin (LTC-USD) mantiene una asignación reducida pero presente \n" \
      "para una diversificación mínima mientras se enfoca en el crecimiento agresivo.")

print("### Comparación de Portafolios (Rendimiento vs. Riesgo) ###\n")

# Crear un DataFrame para comparar los portafolios
portfolio_summary = pd.DataFrame({
    'Portafolio': ['Conservador', 'Moderado', 'Arriesgado'],
    'Rendimiento Anualizado Esperado': [
        portfolio_expected_annual_return,
        portfolio_expected_annual_return_moderate,
        portfolio_expected_annual_return_risky
    ],
    'Volatilidad Anualizada Esperada': [
        portfolio_annual_volatility,
        portfolio_annual_volatility_moderate,
        portfolio_annual_volatility_risky
    ]
})

print("**Resumen Comparativo de Portafolios:**")
print(portfolio_summary.set_index('Portafolio').to_markdown())

# Gráfico de Rendimiento Anualizado Esperado
fig_return_comparison = px.bar(
    portfolio_summary,
    x='Portafolio',
    y='Rendimiento Anualizado Esperado',
    title='Comparación de Rendimiento Anualizado Esperado',
    color='Portafolio',
    color_discrete_sequence=['#1f77b4', '#ff7f0e', '#d62728'], # Colores para cada portafolio
    template='plotly_dark'
)
fig_return_comparison.update_layout(
    yaxis_tickformat='.2%',
    hovermode='x unified'
)
fig_return_comparison.show()

# Gráfico de Volatilidad Anualizada Esperada
fig_volatility_comparison = px.bar(
    portfolio_summary,
    x='Portafolio',
    y='Volatilidad Anualizada Esperada',
    title='Comparación de Volatilidad Anualizada Esperada',
    color='Portafolio',
    color_discrete_sequence=['#1f77b4', '#ff7f0e', '#d62728'], # Colores para cada portafolio
    template='plotly_dark'
)
fig_volatility_comparison.update_layout(
    yaxis_tickformat='.2%',
    hovermode='x unified'
)
fig_volatility_comparison.show()

print("\n**Análisis de la Comparación:**\n")
print("Como se observa en los gráficos, a medida que se transita de un portafolio conservador a uno arriesgado, \n" \
      "el rendimiento esperado anualizado tiende a disminuir en este conjunto de datos específico, lo cual no es lo esperado idealmente. \n" \
      "Esto puede deberse a que los rendimientos promedio diarios de las criptomonedas con mayor volatilidad (SOL, ADA) fueron negativos en el período analizado. \n" \
      "Por otro lado, la volatilidad esperada anualizada aumenta consistentemente, lo cual es de esperar, ya que los portafolios arriesgados incorporan \n" \
      "un mayor porcentaje de activos con mayor dispersión en sus rendimientos. Es crucial que los inversores consideren \n" \
      "estos datos junto con sus propias metas de inversión y tolerancia al riesgo.")

print("### Comparación de Rendimiento Acumulado: Portafolios vs. Benchmark ###\n")

# Calcular los retornos diarios de cada portafolio
portfolio_daily_returns_conservative = df_returns.dot(pd.Series(conservative_weights))
portfolio_daily_returns_moderate = df_returns.dot(pd.Series(moderate_weights))
portfolio_daily_returns_risky = df_returns.dot(pd.Series(risky_weights))

# Calcular los retornos acumulados de cada portafolio
portfolio_cumulative_returns_conservative = (1 + portfolio_daily_returns_conservative).cumprod() - 1
portfolio_cumulative_returns_moderate = (1 + portfolio_daily_returns_moderate).cumprod() - 1
portfolio_cumulative_returns_risky = (1 + portfolio_daily_returns_risky).cumprod() - 1

# Obtener los retornos acumulados del benchmark (BTC-USD)
benchmark_cumulative_returns = df_cumulative_returns[BENCHMARK]

# Crear el gráfico de líneas con Plotly Go
fig_portfolio_comparison = go.Figure()

fig_portfolio_comparison.add_trace(go.Scatter(
    x=portfolio_cumulative_returns_conservative.index,
    y=portfolio_cumulative_returns_conservative,
    mode='lines',
    name='Portafolio Conservador',
    line=dict(color='#1f77b4')
))

fig_portfolio_comparison.add_trace(go.Scatter(
    x=portfolio_cumulative_returns_moderate.index,
    y=portfolio_cumulative_returns_moderate,
    mode='lines',
    name='Portafolio Moderado',
    line=dict(color='#ff7f0e')
))

fig_portfolio_comparison.add_trace(go.Scatter(
    x=portfolio_cumulative_returns_risky.index,
    y=portfolio_cumulative_returns_risky,
    mode='lines',
    name='Portafolio Arriesgado',
    line=dict(color='#d62728')
))

fig_portfolio_comparison.add_trace(go.Scatter(
    x=benchmark_cumulative_returns.index,
    y=benchmark_cumulative_returns,
    mode='lines',
    name=NOMBRES[BENCHMARK] + ' (Benchmark)',
    line=dict(color=COLORS[BENCHMARK], dash='dash') # Benchmark con línea punteada
))

fig_portfolio_comparison.update_layout(
    title_text='Rendimiento Acumulado de Portafolios vs. Benchmark (Bitcoin)',
    xaxis_title='Fecha',
    yaxis_title='Retorno Acumulado',
    hovermode='x unified',
    template='plotly_dark'
)

fig_portfolio_comparison.show()

print("\n**Análisis de Rendimiento Acumulado:**\n")
print("Este gráfico muestra la trayectoria de crecimiento de cada portafolio en comparación con el benchmark de Bitcoin.\n" \
      "Es importante notar que, dado el período analizado y los rendimientos individuales negativos de algunas criptomonedas, \n" \
      "todos los portafolios y el benchmark muestran rendimientos acumulados negativos. \n" \
      "Sin embargo, se puede observar cómo los portafolios con mayor asignación a Bitcoin (como el conservador) tienden a tener una caída menor, \n" \
      "mientras que los portafolios más arriesgados (con mayor exposición a SOL y ADA) presentan una mayor volatilidad y, en este caso, una mayor caída acumulada. \n" \
      "Esto refuerza la idea de que un mayor riesgo puede no siempre traducirse en mayores retornos, especialmente en mercados bajistas, \n" \
      "sino en una mayor magnitud de las fluctuaciones.")

st.set_page_config(page_title="Cripto Dashboard", layout="wide")
st.title("🚀 Análisis Cripto - Concurso 2026")

# Widget interactivo
ticker = st.selectbox("Elige cripto:", ["BTC-USD", "ETH-USD", "SOL-USD", "ADA-USD", "LTC-USD"])
periodo = st.slider("Días de historia:", 30, 730, 365)

# Descarga datos
df = yf.download(ticker, period=f"{periodo}d")
df['retorno'] = df['Close'].pct_change()

# Métricas
col1, col2, col3 = st.columns(3)
col1.metric("Precio actual", f"${df['Close'].iloc[-1].item():,.2f}")
col2.metric("Retorno periodo", f"{(df['Close'].iloc[-1].item()/df['Close'].iloc[0].item()-1)*100:.1f}%")
col3.metric("Volatilidad anual", f"{df['retorno'].std()*(252**0.5)*100:.1f}%")

# Gráfico
fig = px.line(x=df.index, y=df[('Close', ticker)], title=f"Evolución {ticker}")
fig.show()

